name: proxima
channels:
  - defaults
  - psi4
  - conda-forge
dependencies:
  - python==3.6.*
  - pymatgen==2020.1.28
  - scikit-learn==0.21.3
  - tensorflow==2.*
  - tensorflow-probability==0.8.*
  - matplotlib>3
  - ase==3.19.0
  - jupyterlab
  - pytest
  - psi4
  - tqdm
  - pip
  - pip:
      - matminer==0.6.2
      - dscribe==0.3.*
      - python-git-info
      - -e .
  
