# Additional environment details for the monte carlo sampling application
channels:
  - conda-forge
  - psi4
  - defaults
dependencies:
  - pymatgen==2021.2.8
  - scikit-learn==0.22.*
  - matplotlib>3
  - ase==3.19.0
  - psi4
  - pip
  - pip:
    - matminer==0.6.2
    - dscribe==0.3.*
    - python-git-info
    - maml
    - -e .
